// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/bottleneckco/showgrabber/src/backend/model"
)

type SeriesAddInput struct {
	Name   string `json:"name"`
	Status string `json:"status"`
	Banner string `json:"banner"`
}

type SeriesAddPayload struct {
	Ok     bool          `json:"ok"`
	Series *model.Series `json:"series"`
}
